hydra-genetics/alignment

.tests/integration/units.tsv
config/units.tsv
workflow/rules/common.smk
workflow/schemas/units.schema.yaml

Currently there is a column in units.tsv named "unit" which describe data type, e.g Normal (N) or Tumor (T) or RNA (R) sample data. Having a file named units.tsv with a column named unit is a bit confusing.

Refactor units.tsv file

---

.github/workflows/integration1.yaml

feat: run both conda and singularity during integration test

update integration test

---

workflow/rules/bwa_mem.smk
workflow/rules/extract_reads.smk
workflow/rules/mark_duplicates.smk
workflow/rules/merge_bam.smk
workflow/rules/samtools_index.smk

feat: add resources usage to rules.

---

workflow/rules/bwa_mem.smk
workflow/rules/extract_reads.smk
workflow/rules/mark_duplicates.smk
workflow/rules/merge_bam.smk
workflow/rules/samtools_index.smk

fix: handle case when rule have settings but no resources configured.

fix: handle case when rule have settings but no resources configured.

---

.github/workflows/release-please.yaml

feat: added release-please workflow

---

.github/workflows/integration1.yaml
.github/workflows/snakemake-dry-run.yaml
.gitignore
.tests/integration/config.yaml
.tests/integration/config_fastp_pe.yaml
.tests/integration/units.tsv
config/config.yaml
workflow/rules/bwa_mem.smk
workflow/rules/common.smk
workflow/schemas/config.schema.yaml
workflow/schemas/resources.schema.yaml
workflow/schemas/units.schema.yaml

feat: make input for alignment configurable 

---

.tests/integration/config.yaml
.tests/integration/units.tsv
config/config.yaml
config/units.tsv
requirements.txt
workflow/rules/bwa_mem.smk
workflow/rules/common.smk
workflow/schemas/units.schema.yaml

fix: change run column name to flowcell in units.

---

workflow/envs/mark_duplicates.yaml

fix: update conda env

---

workflow/rules/samtools.smk

fix: change version of all samtool wrappers

---

.github/workflows/integration.yaml

feat: add missing software to workflow

---

.github/workflows/integration.yaml

refactor: remove unnecessary install

---

.github/workflows/integration.yaml

feat: lock mamba version

---

.github/workflows/compatibility.yaml

feat: update name of compatibility test

---

workflow/rules/samtools.smk

fix: change to version of samtools sort that uses temp directory

---

.github/workflows/compatibility.yaml
.tests/compatibility/config.yaml
.tests/integration/config.yaml
workflow/envs/samtools.yaml

refactor: remove flag that isn't used

---

workflow/rules/common.smk

fix: also handle unit type T

---

COMPATIBILITY.md
README.md

doc: update compatibility information

docs: update compatibility information

---

.tests/jenkins/Jenkinsfile

fix: set correct jenkins config

---

.tests/jenkins/resources.yaml

chore: update resources.yaml

---

.github/workflows/compatibility.yaml
.github/workflows/integration.yaml
.github/workflows/lint.yaml
.github/workflows/snakemake-dry-run.yaml
.tests/jenkins/Jenkinsfile
workflow/rules/common.smk

feat: make configfile/confgilefiles argument mandatory

---

.github/workflows/integration.yaml

fix: set strict mode for conda

---

COMPATIBILITY.md
README.md

docs: update compatibility list

---

workflow/rules/common.smk

feat(common): update flowcell constraint

---

requirements.txt

fix(requirements): handle tabulate/snakemake bug

---

.tests/jenkins/profiles/slurm/config.yaml

fix: move temp to beegfs-storage

---

.tests/jenkins/Jenkinsfile
.tests/jenkins/slurm/config.yaml

fix: correct jenkins test

---

.tests/jenkins/Jenkinsfile

fix: prevent jenkins from clean on failure

---

.github/workflows/integration.yaml
.github/workflows/snakemake-dry-run.yaml

ci(integration.yaml): lock ubuntu version to 22.04

---

.github/workflows/compatibility.yaml

ci: lock mamba and ubuntu versions

---

.github/workflows/snakemake-dry-run.yaml

ci: remove conda from dry-run

---

COMPATIBILITY.md

docs: update compatibility file

---

.github/workflows/compatibility.yaml
.github/workflows/integration.yaml

refactor: remove unnecessary conda install

---

.github/workflows/integration.yaml

ci: revert changes for integration test singularity

---

.github/workflows/compatibility.yaml
.github/workflows/integration.yaml
.github/workflows/lint.yaml

chore: dev to master

---

.github/workflows/integration.yaml
workflow/envs/bwa.yaml
workflow/envs/picard.yaml
workflow/envs/samtools.yaml
workflow/envs/star.yaml
workflow/rules/bwa.smk
workflow/rules/picard.smk
workflow/rules/samtools.smk
workflow/rules/star.smk

we will drop support for conda, since it constantly breaking even though code hasn't been updated.

ci: remove conda testing

---

README.md

docs: update infiles

---

docs/requirements.txt

mkdocs-yaml-schema-plugin 0.2.2 to 0.2.3
mkdocs-snakemake-rule-plugin 0.3.0 to 0.3.2

chore: update mkdocs-yaml-schema-plugin and mkdocs-snakemake-rule-plugin

---

docs/intro.md
docs/softwares.md
workflow/rules/bwa.smk
workflow/rules/common.smk
workflow/rules/fgbio.smk
workflow/rules/samtools.smk
workflow/schemas/config.schema.yaml
workflow/schemas/resources.schema.yaml
workflow/schemas/rules.schema.yaml

feat: added samblaster for MQ tagging

---

README.md

docs: add link to readthedocs to readme

---

COMPATIBILITY.md
README.md

docs: update compatibility document

---

workflow/Snakefile

feat: add ruleorders so they are not needed in pipeline

---

README.md
config/config.yaml
docs/softwares.md
workflow/Snakefile
workflow/rules/common.smk
workflow/rules/pbmm2.smk
workflow/schemas/config.schema.yaml
workflow/schemas/resources.schema.yaml
workflow/schemas/rules.schema.yaml

feat: Pb2 minor branch merges

---

.github/workflows/integration.yaml

tests: install apptainer for integration test

---

.github/workflows/integration.yaml

test: fix apptainer and conda

---

workflow/rules/common.smk
workflow/rules/minimap2.smk
workflow/rules/pbmm2.smk

feat: set SM tag using wildcards for sample and type

---

workflow/Snakefile

style: rule name order
